[project]
name = "vision-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask>=3.1.0",
    "mediapipe==0.10.9",
    "opencv-python>=4.11.0.86",
    "ruff>=0.11.6",
]
